### ISSUE TITLE
Permetre l'acces dels tèncis especialistes al perfil de tècnic

### ISSUE THREAD

**Issue by andreuperez** [SoftwareProjectUdL/MusicEngine#42]
Sessió ‘Tècnic’ - Apartats: Informe, Sessions, Nòmines, Assignacions, Disponibilitat.
Disponibilitat: Graella amb els dies i hores actuals d’aquest mes.
Disponibilitat: Opció d’escullir el dia del mes i l’hora inici -  hora final de la disponibilitat. Un cop finalitzar opció de guardar.
Disponibilitat: Graella actualizada amb el dies i hores marcats amb l’opció de modificar-ho.

**Comment by gmonso** [comment]
https://github.com/SoftwareProjectUdL/MusicEngine/issues/38
