### ISSUE TITLE
Com a tècnic especialista, m’agradaria poder veure les sol·licituds d’assistència per part de l’empresa.

### ISSUE THREAD

**Issue by andreuperez** [SoftwareProjectUdL/MusicEngine#44]
Sessió ‘Tècnic’ - Apartats: Informe, Sessions, Nòmines, Assignacions, Disponibilitat.
Assignacions: Llista de missatges amb la informació de la sala i el client d’una reserva.
Assignacions: Opcions de confirmar o reburjar la sol·licitud. Un cop decidit és guardarà les sol·licituds escollides i s’enviaràn com a resposta al Personal de Gestió.
Assignacions: Llista de les sol·licituds resoltes amb l’estat(confirmat/rebutjat) actualitzat.

**Comment by gmonso** [comment]
https://github.com/SoftwareProjectUdL/MusicEngine/pull/55
